### ISSUE TITLE
Feature Request: Configs/Settings Tied To Increasing Power of Weapons

### ISSUE THREAD

**Issue by Bubby0304** [TheMarstonConnell/randomloot#6]
I have been enjoying the mod in a pack I made, but I have noticed that the weapons quickly start to outpace other weapons in the pack (despite me already lowering the spawn rate of the loot case's). I would appreciate if there was a way to cap the stats/damage that these weapons can get, or to modify the rate at which opening new cases increase the stats of future openings. That or a config that makes the stats entirely random instead of increasing in strength as you find them.

**Comment by TheMarstonConnell** [comment]
This has been added in the config in v0.0.0-alpha.11
